# Question 1:

In [1]:
import numpy as np

arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2:

In [4]:
print('enter the elements of list 1:')
list1 = [int(input()) for i in range(5)]
arr1 = np.array(list1)

print('enter the elements of list 2:')
list2 = [int(input()) for i in range(5)]
arr2=np.array(list2)

arr = np.concatenate((arr1,arr2))
print(arr)

print(np.sort(arr1))
print(np.sort(arr2))
print(np.sort(arr))


enter the elements of list 1:
2
4
9
1
14
enter the elements of list 2:
11
3
17
15
8
[ 2  4  9  1 14 11  3 17 15  8]
[ 1  2  4  9 14]
[ 3  8 11 15 17]
[ 1  2  3  4  8  9 11 14 15 17]


# Question 3:

In [21]:
nums =np.arange(9).reshape(3,3)
arr_2d=np.array(nums)

#dimensions of the array

print(f'dimension : {arr_2d.ndim}')

#size of the array

print(f'size : {arr_2d.size}')

dimension : 2
size : 9


# Question 4:

In [14]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

arr1 = arr[:,np.newaxis]
print(arr1)
print(arr1.shape)

arr2=np.expand_dims(arr,axis=0)
print(arr2)
print(arr2.shape)

(6,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[[1 2 3 4 5 6]]
(1, 6)


# Question 5:

In [15]:
arr1 = np.arange(1,17).reshape(4,4)
arr2 = np.arange(17,33).reshape(4,4)

# vstack()
arrv = np.vstack((arr1,arr2))
print(arrv)

# hstack()
arrh = np.hstack((arr1,arr2))
print(arrh)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


# Question 6:


## np.unique function can be used to get the unique items.By passing the argument return_counts=True  along with the array we get the unique items and their count

In [19]:
arr = np.array([1,1,1,1,2,2,2,3,3,5,5,1,1,10])

unique , counts = np.unique(arr,return_counts=True)
x = np.asarray((unique,counts)).T

print(x)

[[ 1  6]
 [ 2  3]
 [ 3  2]
 [ 5  2]
 [10  1]]
